# Generated by Django 5.0.3 on 2024-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
